# Generated by Django 5.2.4 on 2025-07-28 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_django_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuprequest',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='executor',
            field=models.ForeignKey(blank=True, help_text='Исполнитель заявки (курьер)', limit_choices_to={'role__name__in': ['courier', 'executor', 'исполнитель']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pickup_requests', to='bot_django_app.user'),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('completed', 'Выполнена'), ('cancelled', 'Отменена')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='type',
            field=models.CharField(choices=[('deliver', 'Доставка на склад'), ('withdraw', 'Вывоз со склада')], default='deliver', max_length=10),
        ),
        migrations.AddField(
            model_name='pickuprequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='address',
            field=models.TextField(help_text='Адрес для забора или доставки вещей'),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requests', to='bot_django_app.user'),
        ),
    ]
