# Generated by Django 5.2.4 on 2025-07-25 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_django_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percent', models.PositiveIntegerField(help_text='Скидка в процентах, например: 20')),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='box',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_django_app.client'),
        ),
        migrations.AlterField(
            model_name='box',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot_django_app.storagelocation'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot_django_app.box'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_django_app.client'),
        ),
        migrations.AlterField(
            model_name='ordersource',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_django_app.client'),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_django_app.client'),
        ),
        migrations.CreateModel(
            name='PromoUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_django_app.client')),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_django_app.promocode')),
            ],
        ),
        migrations.CreateModel(
            name='StoredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bot_django_app.box')),
            ],
        ),
    ]
