# Generated by Django 5.2.4 on 2025-07-26 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_django_app', '0002_promocode_alter_box_client_alter_box_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('volume_m3', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='BoxAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_boxes', models.PositiveIntegerField(default=0)),
                ('occupied_boxes', models.PositiveIntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_django_app.storagelocation')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_django_app.boxsize')),
            ],
        ),
        migrations.AlterField(
            model_name='box',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bot_django_app.boxsize'),
        ),
    ]
